<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Upload Gambar Produk</name>
   <tag></tag>
   <elementGuidId>12dffea7-aa7b-4c41-ab87-f4646e44c405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62291d55-9380-4f5f-ba21-145155e3aea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27179ac8-3d1b-43c0-b17c-007b7055fa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>melaka-add-product__field__product-photo-add-7</value>
      <webElementGuid>57390fe3-836a-4302-be83-3a430f4b15ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N300 flex h-[120px] w-[120px] items-center justify-center rounded-[0.25rem] border border-dashed</value>
      <webElementGuid>454a80ee-cccf-4e6f-8344-158736718aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>b01c9a49-920c-4357-9d69-37dfb170c346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r4j:&quot;)/div[@class=&quot;bg-white p-5 md:p-6 md:rounded-b-2xl&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;flex w-full flex-col gap-2&quot;]/div[2]/div[@class=&quot;flex flex-wrap gap-x-6 gap-y-3&quot;]/button[@class=&quot;border-neutral-N300 flex h-[120px] w-[120px] items-center justify-center rounded-[0.25rem] border border-dashed&quot;]</value>
      <webElementGuid>8fb371d1-3539-4ead-848b-f093f9b7cd12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>58d1c8e9-78ed-4590-9a65-64e2388140de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r4j:']/div/div/div/div[2]/div/button[7]</value>
      <webElementGuid>8dceeddf-6c4b-4831-a10d-24805b5bf54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::button[7]</value>
      <webElementGuid>e88ad3bd-8386-4fa6-a583-5981da80414a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::button[3]</value>
      <webElementGuid>5b147271-de6c-4b70-b4dc-d0a93084eb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]</value>
      <webElementGuid>7868bc58-4dfe-4721-9fd5-5eec039700c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>745c24a3-ce4c-486b-a845-84c422e02cd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
