<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input BPOM Produk</name>
   <tag></tag>
   <elementGuidId>4c37c18c-67d7-4770-96e4-d9fef5db08b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-:r52:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9174b1f4-8f0e-491a-bb2c-30fbda88d2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor BPOM</value>
      <webElementGuid>3390363b-eb27-4083-abda-2553021af3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-disabled border-neutral-N300 enabled:text-he disabled:border-neutral-N300 peer block w-full rounded border p-4 text-base leading-6 placeholder-transparent enabled:focus:outline-none enabled:focus:ring-1 disabled:cursor-not-allowed enabled:focus:border-blue-B700 enabled:focus:ring-blue-B700 placeholder:text-le flex md:w-[320px]</value>
      <webElementGuid>2f2ff2e1-c4ea-485c-89bf-ec2dfce90983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>masterProduct.bpomNumber</value>
      <webElementGuid>20a82ed7-f026-4256-9fe2-10b03a9a6b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-:r52:</value>
      <webElementGuid>01584477-80c2-4c3b-b979-2f3e94b6899e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98008b08-5c7f-4d32-9dfa-d4b0bf697850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>melaka-add-product__field__product-bpom-value</value>
      <webElementGuid>7c03fe17-6dfe-49c7-a5c7-f513c84694a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-:r52:&quot;)</value>
      <webElementGuid>1dc649be-31b3-4b86-9f28-2728e700c000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-:r52:']</value>
      <webElementGuid>bcf106e2-9b8e-4e82-b4f5-d8e680c79e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r4j:']/div[2]/div/div[6]/div[2]/div/div/input</value>
      <webElementGuid>8b87120b-7f26-466f-82e7-2676f391cd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>e48fe648-cce3-4c02-947b-1f2e4baeefa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nomor BPOM' and @name = 'masterProduct.bpomNumber' and @id = 'input-:r52:' and @type = 'text']</value>
      <webElementGuid>20d0b39d-4bb7-4e81-9fbc-3b6174b81add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
