<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input SNI Produk</name>
   <tag></tag>
   <elementGuidId>ad0e0660-96cb-46c9-8fc6-5240f116ab7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-:r53:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a665b1ad-259d-4b98-99c0-183043f35554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor SNI</value>
      <webElementGuid>8790ff77-0091-42b1-88c9-29ad695627f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-disabled border-neutral-N300 enabled:text-he disabled:border-neutral-N300 peer block w-full rounded border p-4 text-base leading-6 placeholder-transparent enabled:focus:outline-none enabled:focus:ring-1 disabled:cursor-not-allowed enabled:focus:border-blue-B700 enabled:focus:ring-blue-B700 placeholder:text-le flex md:w-[320px]</value>
      <webElementGuid>7f24b3af-da37-4028-b869-06cd09cb4523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>masterProduct.sniNumber</value>
      <webElementGuid>38abc8d9-cb87-414b-ad89-e75275f133d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-:r53:</value>
      <webElementGuid>de1dd39e-b1cb-4577-ae13-256b67948e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1367cf79-700c-4c66-a99b-ec3803826b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>melaka-add-product__field__product-sni-value</value>
      <webElementGuid>bbab664f-3661-4186-9ad7-f7fd79bae99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-:r53:&quot;)</value>
      <webElementGuid>548fc623-e7dc-4418-876b-d3657ca7f924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-:r53:']</value>
      <webElementGuid>e3b0814c-0144-4887-9d39-4ebce5185e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r4j:']/div[2]/div/div[7]/div[2]/div/div/input</value>
      <webElementGuid>a1232730-6053-4dfd-8e64-d477c9ce8001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>6ea324d0-8ce8-436a-ab05-46b1ee5cae0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nomor SNI' and @name = 'masterProduct.sniNumber' and @id = 'input-:r53:' and @type = 'text']</value>
      <webElementGuid>12002fe7-ca96-4cf6-8301-4042977fffc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
