<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Varian Produk</name>
   <tag></tag>
   <elementGuidId>535c462b-1d39-45e3-bf5f-467d39036be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-listbox-button-:r4p:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a03cdbe3-5e72-4459-bd81-11b1953b89fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N0 text-he relative w-full cursor-default rounded border p-4 pr-10 text-left focus:outline-none sm:text-sm border-neutral-N300</value>
      <webElementGuid>7664ac3f-5f56-46fd-87c5-f815d33230a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-listbox-button-:r4p:</value>
      <webElementGuid>c96cadf8-9620-4f61-b094-536b5ee71636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13f8f0bb-35bd-4298-aaac-3d11f242c46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>7f9ceb38-7354-4f0b-af74-4ed41d34035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b72632a6-6687-4bbe-9741-effdbea99c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>headlessui-listbox-label-:r4q: headlessui-listbox-button-:r4p:</value>
      <webElementGuid>4633e3d5-6c30-4ad4-aa4c-e18d74771f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baru</value>
      <webElementGuid>5d7ad16f-9f00-44b6-a3d1-9be65c76f2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-button-:r4p:&quot;)</value>
      <webElementGuid>91b118d3-2cf7-46a1-b81f-f8b5fa25c9f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-listbox-button-:r4p:']</value>
      <webElementGuid>3ef177c8-0bd5-4498-98ec-ffd7f5f2ac0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r4j:']/div[2]/div/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>4baca43c-0dd8-4da3-a15c-d8cf7e7315d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::button[1]</value>
      <webElementGuid>4b1d790b-0e08-4653-8e67-f0699f58c3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Produk'])[1]/preceding::button[1]</value>
      <webElementGuid>0f56053c-885f-4d56-890b-e2df0179f2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/button</value>
      <webElementGuid>3e99fb98-328e-4765-814a-c90f0f3f8a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-listbox-button-:r4p:' and @type = 'button' and (text() = 'Baru' or . = 'Baru')]</value>
      <webElementGuid>23f14c1d-1aab-49c6-be58-5b87eb64f111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
