<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Konfirmasi Register</name>
   <tag></tag>
   <elementGuidId>327715f9-1ab8-45aa-81f5-6605931ce18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register__checkbox__tnc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register__checkbox__tnc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>557db100-1e93-41ce-be0c-1ac1d9335136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>472de8d6-b7e5-4fdc-8340-f613c9b6df8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>8bb7b29e-6dee-48b2-811f-12d6901ba001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isTncChecked</value>
      <webElementGuid>fa5178cb-1bc4-4888-b4fd-af48d2de2765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>af34fff8-5918-48d9-8e4f-b4fb851d5778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-blue-B700 border-neutral-N400 h-5 w-5 cursor-pointer rounded border-2 focus:outline-0 focus:ring-transparent disabled:text-neutral-N200 disabled:border-neutral-N200 disabled:cursor-not-allowed checked:disabled:text-blue-B400 checked:disabled:border-blue-B400 indeterminate:disabled:text-blue-B400 indeterminate:disabled:border-blue-B400</value>
      <webElementGuid>2f3cbbf5-a609-421d-8631-f733f977820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>78652718-4600-425e-b4a6-368bb1fd2a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register__checkbox__tnc&quot;)</value>
      <webElementGuid>f11d4f09-18df-4983-9d0d-24197822d499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register__checkbox__tnc']</value>
      <webElementGuid>c4e5a3fb-7677-4b12-8beb-0ab12dd27021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[8]/div/input</value>
      <webElementGuid>8d947c66-eac6-4291-9a8e-999b47b58c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>20dc7aa7-a247-435c-906e-adef894797cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register__checkbox__tnc' and @name = 'isTncChecked' and @type = 'checkbox']</value>
      <webElementGuid>0c260d04-37f9-4256-87ae-45f16ab396e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
